### ISSUE TITLE
Video not saving in circle shape !!

### ISSUE THREAD

**Issue by ritesh94** [safetysystemtechnology/circle-video-record#5]
How do you save the video in circle shape ?

**Comment by NetoDevel** [comment]
The video is saved in an original way, we chose this approach because it is interesting for our use. if you want to change you can open a pull request, we are open to contributions.

Thanks

**Comment by ritesh94** [comment]
Do you have any idea of saving video in a circle shape?

**Comment by NetoDevel** [comment]
Unfortunately not :/

**Comment by ritesh94** [comment]
ok thanks. I was too looking for recording and saving in circle shape

**Comment by lucazin** [comment]
callback is not called
